### PR TITLE
Pass Resources as Context is uneeded

### PR DESCRIPTION
**Pull request by goncalossilva**
Adheres better to the principle of least privilege.

### CODE REVIEW

**Review by JinneeJ — APPROVED** [review]
@goncalossilva Great changes!

What do you think about not removing constructor that accepts `Context context` but marking it as deprecated?

**Comment by goncalossilva** [comment]
That's fine by me @JinneeJ 😄 Want me to make the change, or will you do it?

**Comment by JinneeJ** [comment]
@goncalossilva Please make it since it's in scope of this PR :)

**Comment by goncalossilva** [comment]
Done 👍

**Pull request merged**
